default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo-fmt-check
        entry: bash -c 'cargo fmt --check'
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: cargo-check
        name: cargo-check
        entry: bash -c 'cargo check --workspace'
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: cargo-nextest
        name: cargo-nextest
        entry: bash -c 'cargo nextest run --workspace'
        language: system
        pass_filenames: false
        stages: [pre-push]